name: mapsims

channels:
    - astropy
    - conda-forge

dependencies:
    - python>=3.6
    - astropy
    - Cython
    - toml
    - numba
    - matplotlib
    - numpy
    - sphinx-astropy
    - healpy
    - pip:
        - https://github.com/healpy/pysm/archive/master.zip
        - https://github.com/simonsobs/so_pysm_models/archive/master.zip
