
nside = 16
channels = "SA_27"
unit = "uK_CMB"
mapsims_version = "0.1"
so_pysm_models_version = "0.1"
tag = "test_sim"

[ other_components ]

    [ other_components.noise ]

    class = "mapsims.SONoiseSimulator"
    return_uK_CMB = true
    sensitivity_mode = "baseline"
    apply_beam_correction = true
    apply_kludge_correction = true
    scanning_strategy = "classical"
    LA_number_LF = 1
    LA_number_MF = 4
    LA_number_UHF = 2
    SA_years_LF = 1
    SA_one_over_f_mode = "pessimistic"
    seed = 8974

[ pysm_components ]

    # Remove this if no default PySM components are needed
    pysm_components_string = "a1"
    pysm_output_reference_frame = "G"

    [ pysm_components.dust ]

    class = "so_pysm_models.GaussianDust"
    has_polarization = true
    TT_amplitude = 350
    Toffset = 18
    EE_amplitude = 100
    rTE = 0.35
    EtoB = 0.5
    alpha = -0.42
    beta = 1.53
    temp = 19.6
    nu_0 = 353
    seed = 20001

    [ pysm_components.synchrotron  ]

    class = "so_pysm_models.GaussianSynchrotron"
    has_polarization = true
    TT_amplitude = 20.0
    Toffset = 72
    EE_amplitude = 4.3
    rTE = 0.35
    EtoB = 0.5
    alpha = -1.0
    beta = -3.1
    curv = 0
    nu_0 = 23
    seed = 30001

    [ pysm_components.cmb ]
    class  =  "mapsims.SOPrecomputedCMB"
    iteration_num = 0
    lensed = false
    # At NERSC use:
    # lensed = true
    aberrated = false
    has_polarization = true
    cmb_set = 0
    cmb_dir = "mapsims/tests/data"
    # At NERSC use:
    # cmb_dir = "/global/project/projectdirs/sobs/v4_sims/mbs/cmb"
    input_units = "uK_CMB"
